# This is a basic workflow to help you get started with Actions

name: Create Windows Executable Multichannel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "feature/multichannel" ]
    paths-ignore:
        - 'diagrams/**'
        - 'docs/**'
  pull_request:
    branches: [ "feature/multichannel" ]
    paths-ignore:
      - 'diagrams/**'
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'feature/multichannel'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # Gradle
      - name: Grant execute permission for
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run createExe
        run: ./gradlew createExe

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: JamSketchMultichannel-executable
          path: build/launch4j/
